disabled = false
languageCode = "es"
languageName = "Spanish"
weight = 1
title = "Hackers Week"

[params]
  displayName = "ES"
  isoCode = "es"
  rtl = false
  dateFormat = "2 January 2006"
  description = "La semana Hackers Week es la semana cultural de la Escuela Técnica Superior de Ingeniería Informática organizada por el Consejo de Estudiantes"
  logo = "img/light-logo.png"
  secondaryLogo = "img/dark-logo.png"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Hackers Week"
  image = "img/author-logo.png"
  headline = "Próxima edición del 10 al 14 de marzo de 2025"
  links = [
    { x-twitter = "https://twitter.com/HackersWeek" },
    { instagram = "https://www.instagram.com/hackersweek/" },
    { twitch = "https://www.twitch.tv/consejoinfuma" },
    { github = "https://github.com/ConsejoInfUMA/HackersWeekWeb" },
    { linkedin = "https://www.linkedin.com/in/consejo-inform%C3%A1tica-uma-57a9aa292/" },
    { email = "mailto:hackersweek@uma.es" },
  ]
