# -- Main Menu --
[[main]]
  name = "Información"
  pageRef = "about"
  weight = 2

[[main]]
  name = "Anuncios"
  pageRef = "announcements"
  weight = 5

# [[main]]
 # name = "Eventos"
 # pageRef = "events/2023-24/hackers-days-16-10"
  # weight = 10


#[[main]]
#  name = "Talleres"
#  pageRef = "events/2023-24/hackers-week/workshop"
#  parent  = "Eventos"
#  weight = 12


#[[main]]
#  name = "Torneos"
#  pageRef = "events/2023-24/hackers-week/activities/tournament"
#  parent  = "Eventos"
#  weight = 21

#[[main]]
#  name = "Rol"
#  pageRef = "events/2023-24/hackers-week/activities/rol"
#  parent  = "Eventos"
#  weight = 22

[[main]]
  name = "Prensa"
  pageRef = "press-kit"
  weight = 25

[[main]]
  name = "Histórico"
  pageRef = "events"
  weight = 30

[[main]]
  name = "2023-24"
  pageRef = "events/2023-24"
  parent = "Histórico"
  weight = 30

[[main]]
  name = "2022-23"
  pageRef = "events/2022-23"
  parent = "Histórico"
  weight = 31

[[main]]
  name = "2021-22"
  pageRef = "events/2021-22/hackers-week-8/"
  parent = "Histórico"
  weight = 32

[[main]]
  name = "Hackers Week 11"
  pageRef = "announcements/hackers-week-11/"
  weight = 40

#[[subnavigation]]
#  name = "Información"
#  pageRef = "tags/info"
#  weight = 100

#[[subnavigation]]
#  name = "Ciberserguridad"
#  pageRef = "tags/cybersecurity"
#  weight = 101

#[[subnavigation]]
#  name = "Cuántica"
#  pageRef = "tags/quantic"
#  weight = 102

#[[subnavigation]]
#  name = "Salud"
#  pageRef = "tags/health"
#  weight = 103

#[[subnavigation]]
#  name = "DevOps"
#  pageRef = "tags/devops"
#  weight = 104

# -- Footer Menu --
[[footer]]
  name = "Etiquetas"
  pageRef = "tags"
  weight = 10
